# S02 T04 Programació numèrica
## Nivell 1
### Exercici 1
***Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.***

In [ ]:
def resum_Statistics(fArray):

    if fArray.ndim > 1:
        print ( "El nombre de dimensions de la matriu {} es superior a 1\n".format(fArray))
    else:
        print ( "Les estadístiques de la matriu {} son:".format(fArray))
        print("Suma d'elements : {}".format(fArray.sum()))
        print("Màxim           : {}".format(fArray.max()))
        print("Mínim           : {}".format(fArray.min()))
        print("Mitjana         : {}".format(fArray.mean()))
        print("Mediana         : {}".format(np.median(fArray)))
        print("Desviació Std   : {}\n".format(np.std(fArray)))


In [ ]:
import numpy as np
npArray1=np.array([1,3,5,6,73,5,21,3,5,6,73,5,12,13,5,6,73,5,5,73,6,5,22,1])
npArray2=np.array([[1,3,5,6,73,5,21,3,5,6,73,5,12,13,5,6,73,5,5,73,6,5,22,1]])




In [ ]:
resum_Statistics(npArray1)
resum_Statistics(npArray2)

### Exercici 2
***Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100..***

***IMPORTANT:Entenc que vol dir crear una matriu cuadrada amb nombres aleatoris***

In [ ]:
import random as rd
import numpy as np

In [14]:
def crea_Quadrat(longitud):
    # Definim un array de 1d amb el total d'elements
    rango=longitud*longitud
    fArray = np.empty(rango,dtype=int)
    for i in range(rango): # Afegim els elements
        fArray[i]=rd.randint(0,100)
    fArray.resize(longitud,longitud)
    return fArray

In [15]:
dimQuadrat=int(input("Longitud costat N"))
npQuadrat=crea_Quadrat(dimQuadrat)
npQuadrat

Longitud costat N5


array([[ 53,  61,  48,  17, 100],
       [ 48,   9,  12,  85,  12],
       [ 51,  61,   4,  22,   0],
       [ 27,  57,  60,  56,  88],
       [ 34,  92,  13,  62,  18]])

### Exercici 3
***Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna, faig servir la funció que em genera una matriu de 2 dimensuions**

In [16]:
def suma_Eixos(fArray,eix):
    print("La suma del eix {} es {}".format(eix,fArray.sum(axis=eix)))


In [17]:
dimQuadrat=int(input("Longitud costat N"))
npQuadrat=crea_Quadrat(dimQuadrat)
print("La taula generada es\n {}".format(npQuadrat))
print("Suma las filas")
suma_Eixos(npQuadrat,1)
print("Suma las columnes")
suma_Eixos(npQuadrat,0)


Longitud costat N5
La taula generada es
 [[ 5 36 62 56 72]
 [18 37  8 58 31]
 [64 67 86 86 99]
 [24 22 59 71 43]
 [51  5 89 11  7]]
Suma las filas
La suma del eix 1 es [231 152 402 219 163]
Suma las columnes
La suma del eix 0 es [162 167 304 282 252]


### Exercici 4
***Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.***

****La formula de la correlació  es Covariança(xy)/( DesviacioTipica(x)*DesviacioTipica(y))****

* Segon s'han de calcular las variances de cada serie 
*                 VariançaX=suma((Xi-MitjanaX)\**2)/N
* Tercer hem de calcular la deviació tipica per cada serie 
*                 DesviacioX=Sqr(varianca(X)
* Quart la covaraiaça
*                 CoVariançaXY=suma_i((Xi-promig(X)*(Yi-promig(Y))/N*
* Finalment coef correlacio  r =CoVariançaXY/(DesviacioX*DesviaciY)



***Importem llibreries***

In [2]:

import random as rd
import numpy as np
import math

***calcul promig , podriem utilitzar la funció mean***


In [3]:
#promig de la serie
def calc_promig(parray):
    return (parray.sum()/len(parray))

***calculem la variança= sum_i(Xi-promig(X))/N***
***N=longitud serie***

In [4]:
#Calcula de la varaiança
def calc_varian(parray):
    varian=0
    promig=calc_promig(parray)
    for i in parray:
        varian+=(i-promig)**2
    return (varian/len(parray))

***calculem la desviacio std= sqrt(variança(X)***


In [5]:
#calcula desviació standard
def calc_devstd(parray):
    return math.sqrt(calc_varian(parray))

***calculem la covaraiaça=sum_i((Xi-promig(X)*(Yi-promig(Y))/N***


In [6]:
#calcul de la covariança
def calc_covar(parray1,parray2):
    sumprodXiYi=0
    promig1=calc_promig(parray1)
    promig2=calc_promig(parray2)
    tamany=len(parray1)
    # suma derls productes element a element de les dues series
    for i in range(tamany):
        sumprodXiYi+=((parray1[i]-promig1)*(parray2[i]-promig2))

    covarian=sumprodXiYi/tamany
    return(covarian)

****Finalment calculem el  coef correlacio =CovariançaXY/(DesviacioX*DesviaciY)***

In [7]:

def calc_coef_corr(parray1, parray2):
    coefCorr = calc_covar(parray1,parray2) / (calc_devstd(parray1)* calc_devstd(parray2))
    return (coefCorr)

***Joc de proves i calcul, en el 

In [23]:



#definom Joc de proves amb serie que representa % de persones que acaben estudis per nois i per noies

grad_nois =np.array([39.6,42.7,46,49.9,52.6,55.2,55.6,55.6,56.2,59.6,61.7])
grad_noies=np.array([53.9,55.5,59.6,63,65.5,67,66.4,65.6,66.5,68.9,73.1])
print("Exemple 1 Series amb correlació forta")
print("Coeficient correlacio de la serie \n{}\n i la serie \n{} \n es \n  {}".format(grad_noies,grad_nois,calc_coef_corr(grad_noies,grad_nois)))
print("Comprovacio amb la funcio corrcoef{}\n\n".format(np.corrcoef(grad_noies,grad_nois)))

#Sustituim una serie anterior per una de les random
grad_rnd=np.empty(11,dtype=float)
for i in range(10): # Afegim els elements
    grad_rnd[i]=float(rd.randint(0,100))
print(grad_noies)
print (grad_rnd)
print("Exemple 1 Series sense correlacio")
print("Coeficient correlacio de la serie \n {}\n i la serie\n  {} \nes \n  {} ".format(grad_noies,grad_rnd,calc_coef_corr(grad_noies,grad_rnd)))
print("Comprovacio amb la funcio corrcoef{}".format(np.corrcoef(grad_noies,grad_rnd)))

Exemple 1 Series amb correlació forta
Coeficient correlacio de la serie 
[53.9 55.5 59.6 63.  65.5 67.  66.4 65.6 66.5 68.9 73.1]
 i la serie 
[39.6 42.7 46.  49.9 52.6 55.2 55.6 55.6 56.2 59.6 61.7] 
 es 
  0.9867043644878055
Comprovacio amb la funcio corrcoef[[1.         0.98670436]
 [0.98670436 1.        ]]


[53.9 55.5 59.6 63.  65.5 67.  66.4 65.6 66.5 68.9 73.1]
[36.  80.  67.  54.  41.  21.   0.  98.  22.   1.  73.1]
Exemple 1 Series sense correlacio
Coeficient correlacio de la serie 
 [53.9 55.5 59.6 63.  65.5 67.  66.4 65.6 66.5 68.9 73.1]
 i la serie
  [36.  80.  67.  54.  41.  21.   0.  98.  22.   1.  73.1] 
es 
  -0.23187523228878626 
Comprovacio amb la funcio corrcoef[[ 1.         -0.23187523]
 [-0.23187523  1.        ]]
