# S02 T02: Estructura d'una Matriu

### Nivell 1

#### Exercici 1 Estructura matriu
***Crea un np.array d'una dimensió, que inclogui l'almenys 8 nombres sencers, data type int64. Mostra la dimensió i la forma de la matriu.***

In [25]:
import numpy as np

In [26]:
nouArray=np.array([10,8,7,4,3,9,11,20,23,45,13,8],dtype=np.int64)

In [27]:
print("Forma    : "+ str(nouArray.shape))
print("Tipus    : "+ str(nouArray.dtype))
print("Dimensió : "+ str(nouArray.ndim))

Forma    : (12,)
Tipus    : int64
Dimensió : 1


#### Exercici 2 - Valor mitja

In [29]:
print("Valor mitja : " + str(np.average(nouArray)))

Valor mitja : 13.416666666666666


#### Exercici 3 - Matriu bidimensional 5x5

In [53]:
#nouArray2 = np.array([[10,8,7,4,3],,,,])
nouArray1 = np.array([10,8,7,4,3,9,11,20,23,45,13,8,43,12,1,11,7,45,39,88,77,97,77,14,59]).reshape(5,5)
print(nouArray1)
print(" Maximos por eje horizontal" + str(nouArray1.max(axis=1)))
print(" Maximos por eje vertical" + str(nouArray1.max(axis=0)))
#
#print(max(nouArray1[0]))
#print(max(nouArray1[1]))
#p·rint(max(nouArray1[2]))
#print(max(nouArray1[3]))
#print(max(nouArray1[4]))

[[10  8  7  4  3]
 [ 9 11 20 23 45]
 [13  8 43 12  1]
 [11  7 45 39 88]
 [77 97 77 14 59]]
 Maximos por eje horizontal[10 45 43 88 97]
 Maximos por eje vertical[77 97 77 39 88]
